### PR TITLE
Rename collateBody to collectBody

### PR DESCRIPTION
**Pull request by adam-fowler**
Also only require the maxUploadSize instead of the full context

### CODE REVIEW

**Comment by adam-fowler** [comment]
@sliemeobn

**Review by Joannis — APPROVED** [review]
I think this is a nice change, but can we add the old symbol back with deprecation until release?

**Comment by adam-fowler** [comment]
> I think this is a nice change, but can we add the old symbol back with deprecation until release?

Parameters have changed so that won't work. I guess I could add a wrapper function though

**Comment by adam-fowler** [comment]
@Joannis added deprecated method, plus I moved the new function to Core as it doesn't use any Hummingbird symbols

**Pull request merged**
